### ISSUE TITLE
Port RED marking 

### ISSUE THREAD

**Issue by ATCP** [gaoxiongzeng/EAR-NS2#1]
Hi, gaoxiong,

I found that the following code in priority.cc (in line 54) to realize port RED marking is always true, right?
```
((double)rand()/(double)RAND_MAX) < \
	p_max_*(TotalByteLength()-thresh_*mean_pktsize_)/(thresh_max_-thresh_)
```
you might forget to multiply `mean_pktsize_` by `(thresh_max_-thresh_)`

Thanks
Ke

**Comment by gaoxiongzeng** [comment]
Thanks for reporting the bug. Codes are fixed. Fortunately, per-port-red marking was not used in the paper EAR published on APNet'17.
